export { FinanceDashboard } from "./FinanceDashboard";
export { DeanDashboard } from "./DeanDashboard";
export { StudentDashboard } from "./StudentDashboard";
export { StaffDashboard } from "./StaffDashboard";
export { HODDashboard } from "./HODDashboard";
export { StaffAdvisorDashboard } from "./StaffAdvisorDashboard";
export { StudentExcoDashboard } from "./StudentExcoDashboard";
export { StudentAffairsDashboard } from "./StudentAffairsDashboard";
export { InstitutionAdminDashboard } from "./InstitutionAdminDashboard";
